color = input("Enter a Color: ")
pluralNoun = input("Enter a Plural Noun: ")
celebrity = input("Enter the name of a celebrity: ")
print("Roses are ", color)
print(pluralNoun, " is blue")
print("I like ", celebrity)
